"""HANCORE's marketplace registry — the same JSON behind omarchyplugins.com.

The site is the listing. This is the feed. We pin each source to
`listingValidatedCommit` so a push after listing cannot change what
the census described.
"""

import json
import urllib.error
import urllib.request
from urllib.parse import urlsplit
from collections import Counter
from pathlib import Path

REGISTRY_URL = (
    "https://raw.githubusercontent.com/HANCORE-linux/"
    "omarchy-plugin-marketplace/main/registry.json"
)


class RegistryError(Exception):
    pass


MAX_REGISTRY_BYTES = 10_000_000


def fetch(url: str = REGISTRY_URL) -> dict:
    parsed = urlsplit(url)
    if parsed.scheme != "https" or not parsed.hostname:
        raise RegistryError("registry URL must use HTTPS")
    req = urllib.request.Request(url, headers={"User-Agent": "omaudit-census"})
    try:
        with urllib.request.urlopen(req, timeout=60) as resp:
            declared = resp.headers.get("Content-Length")
            if declared:
                try:
                    too_large = int(declared) > MAX_REGISTRY_BYTES
                except ValueError as exc:
                    raise RegistryError("registry returned an invalid Content-Length") from exc
                if too_large:
                    raise RegistryError("registry response exceeds 10 MB")
            body = resp.read(MAX_REGISTRY_BYTES + 1)
            if len(body) > MAX_REGISTRY_BYTES:
                raise RegistryError("registry response exceeds 10 MB")
            return json.loads(body.decode("utf-8"))
    except (urllib.error.URLError, json.JSONDecodeError, TimeoutError) as exc:
        raise RegistryError(f"could not read {url}: {exc}") from exc


def extract(registry: dict) -> tuple[list[dict], dict]:
    sources = registry.get("sources") or []
    retired = set(registry.get("retiredPluginIds") or [])

    entries = []
    for src in sources:
        repo = src.get("repo")
        if not repo:
            continue
        plugin_ids = list((src.get("plugins") or {}).keys())
        if plugin_ids and all(pid in retired for pid in plugin_ids):
            continue
        baseline = src.get("automatedSecurityBaseline") or {}
        entries.append({
            "repo": repo,
            "commit": src.get("listingValidatedCommit"),
            "branch": src.get("listingValidatedBranch"),
            "type": src.get("type"),
            "pluginIds": plugin_ids,
            "baselineOutcome": baseline.get("outcome"),
            "baselineCapabilities": baseline.get("capabilities") or [],
            "baselineFindings": baseline.get("findings") or [],
            "hasBaseline": bool(baseline),
        })

    withb = [e for e in entries if e["hasBaseline"]]
    stats = {
        "sources": len(entries),
        "withUpstreamBaseline": len(withb),
        "baselineOutcomes": dict(Counter(
            e["baselineOutcome"] for e in withb if e["baselineOutcome"])),
        "baselineCapabilityFrequency": dict(Counter(
            c for e in withb for c in e["baselineCapabilities"]).most_common()),
        "baselineFindingCount": sum(len(e["baselineFindings"]) for e in withb),
        "sourcesWithAnyBaselineCapability": sum(
            1 for e in withb if e["baselineCapabilities"]),
    }
    return entries, stats


def spec_for(entry: dict, unpinned: bool = False) -> str:
    if entry.get("commit") and not unpinned:
        return f"{entry['repo']}@{entry['commit']}"
    return entry["repo"]


def write_listing(out: Path, entries: list[dict], stats: dict,
                  unpinned: bool = False) -> dict[str, set[str]]:
    """Write plugins.txt + sidecar JSON. Returns {added, removed} vs the
    previous plugins.txt in the same directory, if any."""
    out.mkdir(parents=True, exist_ok=True)
    lines = [
        "# generated by omaudit census — repo@commit, pinned to the",
        "# commit the marketplace validated at listing time",
    ]
    specs = [spec_for(e, unpinned) for e in entries]
    lines.extend(specs)

    previous = _read_specs(out / "plugins.txt")
    current = set(specs)
    delta = {
        "first": not previous,
        "added": current - previous,
        "removed": previous - current,
    }

    (out / "plugins.txt").write_text("\n".join(lines) + "\n", encoding="utf-8")
    (out / "registry-entries.json").write_text(
        json.dumps(entries, indent=2), encoding="utf-8")
    (out / "upstream-baseline.json").write_text(
        json.dumps(stats, indent=2), encoding="utf-8")
    return delta


def _read_specs(path: Path) -> set[str]:
    if not path.is_file():
        return set()
    return {
        ln.strip() for ln in path.read_text(encoding="utf-8").splitlines()
        if ln.strip() and not ln.startswith("#")
    }
